
kaspad:
  enabled: true
  nameOverride: kaspad

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    replicas: 1
    strategy:
      type: Recreate

    resources:
      limits:
        cpu: 700m
        memory: 3Gi
      requests:
        cpu: 350m
        memory: 2Gi
  
    ports:
      - containerPort: 16110

    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/kaspa/kaspad

    #volumeMounts:
    #  - name: data-dir
    #    mountPath: /home/kaspa/.rusty-kaspa

    volumes:
      - name: data-dir
        persistentVolumeClaim:
          claimName: kaspad-pvc

  service:
    enabled: true
    ports:
      - port: 16110
        targetPort: 16110
        protocol: TCP
        name: grpc-mainnet
