apiVersion: v2
name: helm-kaspa
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Kaspa Apps

dependencies:
  ### kaspad ###
  - name: "generic-app"
    alias: kaspad
    condition: kaspad.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.17"
