apiVersion: v2
name: helm-kaspa
version: 1.0.0
appVersion: 1.23.0
description: A Helm chart wrapper for Kaspa Apps

dependencies:
  ### kaspad ###
  - name: "generic-app"
    alias: kaspad
    condition: kaspad.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.17"

  ### kaspad-rust ###
  - name: "generic-app"
    alias: kaspad-rust
    condition: kaspad-rust.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.17"

  ### kaspad-db-filter ###
  - name: "generic-app"
    alias: kaspad-db-filter
    condition: kaspad-db-filter.enabled
    repository: "https://charts.visonneau.fr/"
    version: "0.0.17"

  ### pgSQL ###
  - name: "postgresql"
    alias: postgresql
    condition: postgresql.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "14.0.5"

  - name: "redis"
    alias: redis
    condition: redis.enabled
    repository: "https://charts.bitnami.com/bitnami"
    version: "18.13.0"
