
kaspad-rust:
  enabled: true
  nameOverride: kaspad-rust

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    additionalContainers:
      - name: kaspa-archive
        image: asia-southeast1-docker.pkg.dev/its-artifact-commons/kaspa/kaspa-misc:develop-d2022f4
        command: ["ruby"]
        args: [ "/scripts/kaspa-data-archive.rb" ]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: data-dir
          mountPath: /app/data/
        - name: temp-dir
          mountPath: /data
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        env:
          - name: ARCHIVE_SRC_DIR
            value: /app/data/kaspa-mainnet
          - name: ARCHIVE_DST_DIR
            value: /data
          - name: ARCHIVE_DELAY_SEC
            value: '43200' # 12 hours
          - name: ARCHIVE_KASPAD_TYPE
            value: rust

    controller: deployment
    command:
      - kaspad
    args:
      - --rpclisten=0.0.0.0
      - --appdir=/app/data/
      - --yes
      - --utxoindex
      - --archival
      #- --rpclisten-borsh=public
      #- --disable-upnp

    replicas: 1
    strategy:
      type: Recreate

    securityContext:
      fsGroup: 999
      runAsUser: 999
      runAsGroup: 999

    resources:
      limits:
        cpu: 3500m
        memory: 8Gi
      requests:
        cpu: 1350m
        memory: 4Gi
  
    ports:
      - containerPort: 16110
      - containerPort: 16111
    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/kaspa/kaspad

    volumeMounts:
      - name: data-dir
        mountPath: /app/data/ #/home/kaspa/.rusty-kaspa

    volumes:
      - name: data-dir
        persistentVolumeClaim:
          claimName: kaspad-rust-pvc
      - name: temp-dir
        emptyDir: {}

  service:
    enabled: true
    ports:
      - port: 16110
        targetPort: 16110
        protocol: TCP
        name: grpc-mainnet

      - port: 16111
        targetPort: 16111
        protocol: TCP
        name: p2p-mainnet
