apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaspad-pvc
spec:
  volumeName: kaspad-pv
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 250Gi
