apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kaspad-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: standard
  volumeMode: Filesystem
