apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaspad-api-ing
  #annotations:
  #  nginx.ingress.kubernetes.io/proxy-body-size: 50m
  #  nginx.org/client-max-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
  - host: "{{ .Values.kaspad.kaspadApiDomain }}"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/"
        backend:
          service:
            name: kaspa-{{ .Values.kaspad.envAlias }}-kaspad
            port:
              number: 16110
