
kaspad-db-filter:
  enabled: false # true
  nameOverride: kaspad-db-filter

  ingress:
    enabled: false

  podDisruptionBudget:
    enabled: false

  pods:
    controller: deployment
    replicas: 1

    resources:
      limits:
        cpu: 200m
        memory: 300Mi
      requests:
        cpu: 50m
        memory: 100Mi

    image:
      name: asia-southeast1-docker.pkg.dev/its-artifact-commons/kaspa/kaspa-db-filter

  service:
    enabled: false
