kaspad-db-filter:
  envAlias: dev
  pods:
    env:
      - name: TZ
        value: Asia/Bangkok

      - name: PgHost
        value: "postgresql"

      - name: PgPort
        value: "5432"

      - name: PgDatabase
        value: "kaspa-filter"

      - name: PgUser
        value: "postgres"

      - name: PgPassword
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: adminPasswordKey
            optional: false

      - name: KaspaNodeUrl
        value: "https://node.kaspium.io:16110"

      - name: KaspaStartBlockHash
        value: "eb463c87f5df8def0720a63681aceba38918958e03b8ca8ada758c0cb6836405"

      - name: DelayMs
        value: "1000"
